name: 'Python Syntax and Linting Checks'
description: 'Checks Python syntax, indentation, and linting for changed files'
inputs:
  files:
    description: 'List of changed Python files'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout self
      uses: actions/checkout@v2

    - name: Run Python Checks
      run: |
        pip install pylint 
        python ${{ github.action_path }}/py-checks.py ${{ inputs.files }}
      shell: bash