name: 'Python Syntax and Linting Checks'
description: 'Checks Python syntax, indentation, and linting for changed files'
inputs:
  files:
    description: 'List of changed Python files'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout self
      uses: actions/checkout@v2

    - name: Install pylint 
      run: pip install pylint 
      shell: bash

    - name: Run Python Checks 
      run: | 
        cd ${{ github.action_path }}/.github/actions/python-checks 
        export PYTHONPATH=${{ github.action_path }}/.github/actions/python-checks:$PYTHONPATH 
        python py-checks.py ${{ inputs.files }} 
      shell: bash